version: '3.3'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  prometheus:
    command:  
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/data/prometheus
    
    container_name: prometheus
    #environment:
    # LISTEN_ADDRESS: 127.0.0.1
    
    
    ports:
      - "9090:9090"        

    image: prom/prometheus:latest
    user: root
    restart: unless-stopped
    networks: 
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/data/prometheus        



  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    restart: unless-stopped
    ports:
      - "9100:9100"

    networks:
      - monitoring    

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana 
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

    restart: unless-stopped
    ports:
      - "3000:3000" 
